# Display a box
print("state the eye shape as 0 or else")
eyes = input()
print("        ####################        ")
print("        #                  #        ")
print(f"        #     {eyes}      {eyes}     #        ")
print("        #                  #        ")
print("        #  \            /  #        ")
print("        #   \__________/   #        ")
print("        ####################        ")
print("             #         #            ")
print("    ##########         ##########   ")
print("    #                           #    ")
print("    #                           #    ")
print("    #                           #    ")
print("    #                           #    ")
print("    #                           #    ")
print("    #    #                 #    #    ")
print("    #    #                 #    #    ")
print("    #######               #######    ")
print("          #       #       #          ")
print("          #       #       #          ")
print("          #       #       #          ")
print("          #       #       #          ")
print("          #       #       #          ")
print("          #       #       #          ")
print("          #       #       #          ")
print("          #################          ")
